name: auth
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.5
  encrypt: ^5.0.3
  grpc: ^4.0.0
  jaguar_jwt: ^3.0.0
  postgres: ^3.3.0
  process_run: ^1.2.0
  protobuf: ^3.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

linter:
  rules:
    - library_prefixes